stentorium/stentor

packages/stentor-models/src/Request/IntentRequest.ts
packages/stentor-models/src/Request/Request.ts

Adds an optional `deviceId` field to the BaseRequest to start passing this through on channels where it is available.  Also adds a `matchConfidence` field to the IntentRequest to provide the intent's confidence when available.
And some docs.

feat: Adding deviceId, matchConfidence to Requests

---

.circleci/config.yml
renovate.json

Updates the renovate config to only update aws-sdk once a week and combines all stentor & @xapp packages into one group and also fixes the circle config to ensure tests are run before release.

fix: Reconfigure Renovate

---

packages/stentor-response/src/index.ts

We have some consumers of this package importing from `stentor-response/lib/Guards` however these are ok to export through the primary API.

fix: Export the guards in stentor-response

---

packages/stentor-handler/package.json

This was unused and causing more circular dependencies.

fix: Removing unused stentor-alexa in stentor-handlers

---

packages/stentor/package.json
packages/stentor/src/Assistant.ts
yarn.lock

The analytics service is a heavy package since it communicates to several 3rd party analytics providers and has their SDKs as dependencies.  It was only needed for a very simple method in stentor so I removed it.

fix: Remove analytics service dependency

---

packages/stentor-handler/src/AbstractHandler/Handler.ts
packages/stentor-handler/src/AbstractHandler/__test__/Handler.test.ts

This fixes a crash that was observed when the handler does not yet have anything on the data field.

fix: Crash within AbstractHandler.canHandlerInputUnknown when handler data is undefined

---

packages/stentor-utils/src/date-time/__test__/isDuration.test.ts
packages/stentor-utils/src/date-time/index.ts
packages/stentor-utils/src/date-time/isDuration.ts
packages/stentor-utils/src/dateTime.ts
yarn.lock

Adds new type guard `isDuration` and modifies `isDateTime` and `isDateTimeRange` to make it slightly easier to consume.

fix: Adding isDuration

---

.circleci/config.yml

This should fix the release build on circle, this setting was unnecessary since we don't use semantic-release.

fix: Remove older node version in circle config

---

packages/stentor-models/src/Entity/Entity.ts
packages/stentor-models/src/Intent/Intent.ts
packages/stentor-models/src/Request/IntentRequest.ts
packages/stentor-models/src/Slot/Slot.ts

This adds the `nlu` field to both a Slot and Entity to allow for overriding the type for a specific NLU.
This field will be taken into account at the time of model translation when updating the NLU.
This will allow models to contain a broader set of entities, those that do not have a abstracted version in stentor.

feat: Ability to override entity type on Slot & Entity for a specified NLU

---

packages/stentor-response/src/__test__/getResponse.test.ts
packages/stentor-response/src/getResponse.ts

Allows you to order which required slots you fill by adding conditionals to the responses.  
For example, you want to fill a date slots before a time slot, you can set a conditional on the time slot to require the date slot and the date slot will be filled first.

feat: Ability to order which slots need filling

---

packages/stentor-response/package.json
packages/stentor/package.json
yarn.lock

Removes unused `actions-on-google` from `stentor-response` and adds the missing `@types/aws-lambda` (not sure how this was working without it).

fix: Removing unused package and adding missing one

---

packages/stentor-models/src/Runtime/RuntimeContext.ts
packages/stentor-runtime/src/ContextUtils.ts
packages/stentor-runtime/src/translateEventAndContext.ts

We didn't return a response when sending events directly to a lambda (never did it before, it was always through API Gateway), this adds a basic lambdaContext util.

fix: Adds basic Lambda Context Util

---

packages/stentor-models/src/Intent/Intent.ts

Similar to the slot model, adding a key value store on the Intent model allows us to do intent specific overrides on the type of intent it will be translated to for the respective NLU (which is the key in the store).

feat: Adds NLU key value store on Intent model 

---

packages/stentor-models/src/UtteranceTest.ts
packages/stentor-models/src/index.ts

These models were previously closed source, isolated in a single package, but are needed for other packages.

fix: Adding UtteranceTest models

---

packages/stentor-runtime/src/ContextUtils.ts
packages/stentor/src/__test__/Assistant.test.ts

Very simple fix. It's needed for the widget to connect from browsers. "cors: true" in the serverless yml is not enough.

fix: Add CORS Header for API Gateway Response

---

packages/stentor-models/src/Request/IntentRequest.ts

Some NLUs, like Amazon LEX, have confidence scores on the slot as well.

fix: Confidence Score on Slot

---

packages/stentor-determiner/src/determine.ts
packages/stentor-interaction-model/src/SlotConditionalCheck.ts
packages/stentor-interaction-model/src/__test__/SlotConditionalCheck.test.ts

A little silly this was in place after discovering this issue but we only added the slot based conditional checks if the intent request had slots.  This then caused a problem for the conditional check `slotExists` because that conditional check wouldn't exist and throw an error.

fix: Slot Conditional Checks had conditional check for adding them

---

packages/stentor-handler/src/AbstractHandler/Handler.ts
packages/stentor-handler/src/AbstractHandler/__test__/Handler.test.ts

When an InputUnknown happens and the data field is undefined, the handler could crash.

fix: Crash with handler.data is undefined

---

packages/stentor/src/Assistant.ts

Context was being passed through instead of the event.

fix: Passing through Context instead of Event

---

packages/stentor-models/src/Channel/Channel.ts

`aws-lambda` was referenced in stentor-models but was not included in the package.json.  Instead of adding it since stenor-models does not have any 3rd party external dependencies, it just copies over the callback definition.

chore: Removes aws-lambda from stentor-models

---

packages/stentor-models/src/Display/List/List.ts

This will help us better support actions on google lists with URLs and chat widget lists with URLs.

fix: Adds URL to Display List Item

---

packages/stentor-channel/src/__tests__/TranslateToStentorResponse.test.ts
packages/stentor-utils/src/__test__/markdown.test.ts
packages/stentor-utils/src/markdown.ts

`\n` is not displayed within HTML however `<br />` achieves what we want.

fix: Convert \n to <br /> tags in markdown

---

packages/stentor-models/src/Request/Request.ts

Some channels provide a unique ID for each request.  This can be helpful down stream for referencing and finding a particular request.

chore: Add optional requestId to BaseRequest

---

packages/stentor-models/src/Intent/Intent.ts
packages/stentor-models/src/Response/Response.ts
packages/stentor-response/src/ResponseBuilder.ts
packages/stentor-response/src/__test__/ResponseBuilder.test.ts

Input contexts are supported by both Amazon Lex & Dialogflow, they allow you to provide additional information to help the NLU pick the intent from the user's query.  They can be extremely helpful when you have multiple potential high confidence intent matches within the NLU for a particular query.

feat: Support for Input Contexts

---

packages/stentor-response/src/__test__/compileResponse.test.ts
packages/stentor-response/src/compileResponse.ts
packages/stentor-utils/src/compilers/__test__/compiler.test.ts
packages/stentor-utils/src/compilers/compiler.ts

Boolean `false` values from JSON Path evaluation turned out to fail the check if results returned or not and then were not compiled.

fix: Ability to now compile boolean false values in responses

---

packages/stentor-models/src/Pii.ts
packages/stentor-models/src/UserProfile.ts

This updates `preciseLocation` on the User Data & PII to use an object consisting of latitude and longitude coordinates.

fix: Update preciseLocation to use coordinates isntead of string.

---

packages/stentor-time/src/__test__/findSchedulableMatch.test.ts

No code changes, just adding a test to confirm we can support decimals on the duration.

chore: Confirms durations can be decimal

---

packages/stentor-handler-manager/src/HandlerManager.ts
packages/stentor-handler/src/AbstractHandler/Handler.ts
packages/stentor-handler/src/AbstractHandler/__test__/Handler.test.ts
packages/stentor-models/src/Context.ts

Small breaking change, modifies two methods on the AbstractHandler to be async.
These two functions are exposed in the public API but are not typically used and the migration is straight forward (just add an async).  I would not recommend a major version bump for this change.

BREAKING CHANGE: Modifies forwardingPathForRequest and redirectingPathForRequest to be async

---

packages/stentor-models/src/Crm.ts
packages/stentor-models/src/Message.ts
packages/stentor-models/src/Request/Request.ts
packages/stentor-runtime/src/__test__/main.storage.test.ts

* Adds an optional request attributes so we can leverage channels that already support them and pass them through.
* Replaces the previous CRM (still unused) service transcript with the same one on the session store.

fix: Add request attributes and update CRM Transcript

---

packages/stentor-runtime/src/__test__/Mocks.ts
packages/stentor-runtime/src/main.ts

Fixes a bug where main would crash when outputspeech didn't exist.

fix: Crash when outputSpeech doesn't exist

---

packages/stentor-models/src/Request/Request.ts

We want the request attributes to be more accessible and `object` is hard to use.  This change is innocuous.
Challenges of `object`:

fix: Changes object to record<string,unknown> on Request Attributes

---

packages/stentor-models/src/NLU/NLUService.ts

We want to surface the match confidence on the NLUService for use and capture.

chore:Adding matchConfidence to NLUServiceResponse

---

packages/stentor-utils/src/compilers/__test__/compiler.test.ts
packages/stentor-utils/src/compilers/compiler.ts

Was getting a crash when the session values were coming back as `null`.  We now look for `null` and protect against it.

fix: Check for null values in the compiler

---

packages/stentor-utils/src/__test__/markdown.test.ts
packages/stentor-utils/src/markdown.ts

Code Blocks, `<code>` caused some oddities when we attempted to display them in the messages:  
This disables them, which is ok as they weren't technically supported in the first place: https://documentation.xapp.ai/docs/content/responses#display-text

fix: Removes support for markdown blocks

---

packages/stentor-logger/src/__test__/logger.test.ts
packages/stentor-logger/src/logger.ts

`stentor-logger` was pretty printing JSON which can be nice for local console however in CloudWatch it just pollutes your log statements with the new lines.
This detects if we are on AWS Lambda and then does not pretty print JSON objects.

fix: Better compatibility with CloudWatch logs

---

packages/stentor-context/src/ContextFactory.ts
packages/stentor-models/src/Context.ts
packages/stentor-models/src/Services/ErrorService.ts
packages/stentor-models/src/Services/index.ts
packages/stentor-runtime/src/main.ts
packages/stentor-service-event/src/EventService.ts

This exposes the event service on the runtime context for reporting errors!  This will allow us to send runtime errors from external APIs to Studio (or other) for tracking.

fix: Adding EventService to runtime context

---

packages/stentor-models/src/Knowledgebase/KnowledgeBaseConfig.ts
packages/stentor-request/src/Builders.ts
packages/stentor-runtime/src/__test__/main.knowledgebase.test.ts
packages/stentor-runtime/src/main.ts
packages/stentor/src/Assistant.ts
packages/stentor/src/__test__/Assistant.test.ts

For some channels, like intelligent-search, we want all requests to go to the KBService.  This adds a new field to the KBConfig to add `matchChannel`.  If this exists it takes precedence over `matchIntentId`

fix: Ability to select KB Service based on Channel

---

packages/stentor-models/src/Request/InputUnknownRequest.ts
packages/stentor-models/src/Request/IntentRequest.ts
packages/stentor-models/src/Request/Request.ts

This prepares us for Dialogflow ES & Lex V2 style sentiment information appended to requests.
Reference
* Lex V2 / [Comprehend](https://docs.aws.amazon.com/comprehend/latest/dg/how-sentiment.html)
* [Dialogflow ES](https://cloud.google.com/dialogflow/es/docs/reference/rest/v2beta1/SentimentAnalysisResult)

fix: Adding Sentiment Analysis Information to IntentRequest and InputUnknownRequest

---

packages/stentor-runtime/src/ContextUtils.ts

Added support for form POST and XML response. I suggest they typed object (type, payload), because Twilio needs the correct Content-Type header.

Form support for incoming payloads, typed native response (ex. XML)

---

packages/stentor-models/src/Services/CrmService.ts

Adds optional ability to send additional metadata to your CRM Service without first extending it.

chore: Add extras to CRM Service Send

---

packages/stentor-channel/package.json
packages/stentor-channel/src/Channel.ts
packages/stentor-models/src/Channel/Channel.ts
packages/stentor-models/src/UtteranceTest.ts
packages/stentor-runtime/src/__test__/Mocks.ts
packages/stentor-runtime/src/__test__/main.channels.test.ts
packages/stentor-runtime/src/__test__/main.hooks.test.ts
packages/stentor-runtime/src/main.ts

When we pass an NLU to the Stentor channel, we now automatically set the hook to send the context to the NLU for the response.

fix: Set Context Support for Stentor Channel

---

packages/stentor-models/src/Services/PodcastSearchService.ts
packages/stentor-models/src/Services/index.ts

Part of cleaning up other repositories, moving this to models allows us to clean up some dependencies in other repositories.

chore: Podcast Search Service

---

packages/stentor-conditional/README.md
packages/stentor-conditional/package.json
packages/stentor-conditional/src/ConditionalDeterminer.ts
packages/stentor-conditional/src/__test__/ConditionalDeterminer.test.ts
packages/stentor-conditional/src/getVM.ts
yarn.lock

For all those having build issues with VM2, it is not optional dependency.  If VM2 is not installed, is uses Node's built-in VM module.  Furthermore, you can also use [isolated-vm](https://www.npmjs.com/package/isolated-vm) which gives you access to V8's Isolate interface, which is an isolated JS runtime.

fix: VM2 now optional dependency

---

packages/stentor-models/src/NLU/NLUService.ts

This updates the `NLUQueryResponse` to now be based on IntentRequest and InputknownRequest, which both contain the KnowledgeBaseResult.
This change will allow you to add the logic of when you call a KnowledgeBaseService to within a custom NLU instead of relying on the built-in logic.

fix: NLUQueryResponse now includes KnowledgeBaseResult

---

packages/stentor-runtime/src/__test__/main.channelactionrequest.test.ts
packages/stentor-runtime/src/main.ts

This adds very simple initial support for the new ChannelActionRequest.  This is subject to change but it is a start and it prevents the runtime environment from erroring.

fix: Initial Support for ChannelActionRequest

---

packages/stentor-models/src/Request/KnowledgeBase.ts

Adds new, optional, field `generated` to better differentiate when we get answers from an LLM.

fix: Adding generated knowledge base response

---

packages/stentor-utils/package.json
renovate.json
yarn.lock

2.30.0 is missing a runtime dependency for babel.

fix: Reverts date-fns back to 2.29.2

---

packages/stentor-models/src/Request/KnowledgeBase.ts

We need a way to determine if the LLM actually has an answer in the generated text or not since it will always generate text.

fix: Adds hasAnswer field to the generated KB answer

---

packages/stentor-runtime/src/combineKnowledgeBaseResults.ts

We didn't have it in the combine results function that puts it on the session variables.

fix: Adding support for Generated KnowledgeBase Answers 

---

packages/stentor-models/src/Response/AbstractResponseBuilder.ts

Missed this one when allowing a array of strings on the tag.

fix: Adding string[] to abstract builder tag

---

packages/stentor-runtime/src/main.ts

Logging the entire handler can really clog your logs and it isn't necessary.

fix: Reduce logging of handler

---

packages/stentor-models/src/Request/IntentRequest.ts

This adds optional active contexts to the IntentRequest to see which contexts are active or not.

fix: Adds active contexts to IntentRequest

---

packages/stentor-handler/src/AbstractHandler/Handler.ts
packages/stentor-handler/src/AbstractHandler/__test__/Handler.test.ts
packages/stentor-models/src/Handler/Data.ts
packages/stentor-response/src/ResponseBuilder.ts
packages/stentor-response/src/__test__/getResponse.test.ts
packages/stentor-response/src/getResponse.ts
packages/stentor-utils/src/__test__/response.test.ts
packages/stentor-utils/src/response.ts

This adds the optional ability to set suggestion chips within a handler's data that are then applied to every response.
It will automatically merge and dedupe suggestions with any existing on the response output.

feat: Adds the ability to set suggestion chips on handler data, which are then applied

---

packages/stentor-models/src/Request/KnowledgeBase.ts
packages/stentor-service-studio/src/StudioService.ts
packages/stentor-utils/src/__test__/matcher.test.ts
packages/stentor-utils/src/matcher.ts
packages/stentor-utils/src/string/__test__/compare.test.ts
packages/stentor-utils/src/string/compare.ts
packages/stentor-utils/src/string/index.ts

Our prefilter on the FAQs is no longer necessary as we are now passing these results to an LLM, which will better determine if they are relevant or not.  The old behavior can still be used through a construction property.

fix: FAQ Prefiltering no longer default on StudioService

---

packages/stentor-models/src/Crm.ts

We can use these to keep track of sessionId and userId in our lead system for later lookup.

fix: Adding sessionId & userId to ExternalLead

---

packages/stentor-handler-factory/src/HandlerFactory.ts

Problem was the class names get obfuscated and don't work anymore.

fix: Strings for Handler Map Keys
