renovate.json
Groups all stentor packages and accept xapp packages at anytime.
=> chore: Update Renovate Configuration

packages/stentor-models/src/Channel/Channel.ts, packages/stentor-runtime/src/__test__/Mocks.ts, packages/stentor-runtime/src/__test__/main.hooks.test.ts, packages/stentor-runtime/src/main.ts, packages/stentor-utils/src/__test__/number.test.ts, packages/stentor-utils/src/index.ts, packages/stentor-utils/src/number.ts, packages/stentor-utils/src/request/__test__/requestSlotValueToString.test.ts, packages/stentor-utils/src/request/index.ts, packages/stentor-utils/src/request/requestSlotValueToString.ts
Adds one more hook available to the channels.  Also adds to more util functions that are needed in other packages.
=> feat: Adding postRequestTranslation to the Channel Hooks

packages/stentor-models/src/NLU/NLUService.ts, packages/stentor-models/src/Response/AbstractResponseBuilder.ts, packages/stentor-models/src/Response/Response.ts, packages/stentor-response/src/ResponseBuilder.ts
Adding handoff request to the abstract builder
=> feat: Hand-off Response - Transfer to Live Agent

packages/stentor-handler/package.json, packages/stentor-handler/src/HandlerGraph/HandlerGraph.ts, packages/stentor-interaction-model/src/Intent/UtteranceGenerator.ts, packages/stentor-locales/package.json, packages/stentor-media/package.json, packages/stentor-media/src/__test__/determinePlayableMedia.test.ts, packages/stentor-response/package.json, packages/stentor-runtime/src/__test__/Canfulfill.test.ts, packages/stentor-storage/src/StorageAction/StorageActionExecutorFactory.ts, packages/stentor-utils/package.json, packages/stentor-utils/src/__test__/json.test.ts, packages/stentor-utils/src/array.ts, renovate.json
This removes some unnecessary dependencies and in some cases replaces them with native functionality.
Also slight tweak to the Renovate config to reduce the automated builds.
=> fix: Remove unnecessary dependencies (Renovate Update)

packages/stentor-context/src/ContextBuilder.ts, packages/stentor-context/src/__test__/ContextFactory.test.ts, packages/stentor-handler-factory/src/__test__/HandlerFactory.test.ts, packages/stentor-handler-manager/src/__test__/HandlerManager.test.ts, packages/stentor-handler/src/AbstractHandler/__test__/Handler.test.ts, packages/stentor-handler/src/__test__/ConversationHandler.test.ts, packages/stentor-models/src/Device.ts, packages/stentor-response/src/__test__/ResponseBuilder.test.ts, packages/stentor-runtime/src/__test__/ChannelSelector.test.ts, packages/stentor-runtime/src/__test__/Mocks.ts, packages/stentor/src/__test__/TestChannel.ts
We need this for active buttons (G assistant app for instance)
=> Has web browser in device

packages/stentor-constants/src/storage.ts, packages/stentor-context/src/ContextBuilder.ts, packages/stentor-determiner/src/determine.ts, packages/stentor-request/package.json, packages/stentor-request/src/SystemConditionalCheck.ts, packages/stentor-request/src/__test__/SystemConditionalCheck.test.ts, packages/stentor-runtime/src/__test__/main.storage.test.ts, packages/stentor-runtime/src/main.ts
This adds some conditional macros:
Determines if the user is brand new, will be true for the length of the first session
```
isNewUser()
```
Determine if the request is for the provided platform.
```
isPlatform(platform: string)
```
Check either session storage or storage the provide key equals the provided value.
```
storageEquals(key: string, value) || sessionStorageEquals(key: string, value)
```
=> feat: Adding a couple new helpful conditional macros

packages/stentor-constants/src/entities.ts
Will add an abstracted STENTOR.PERSON, which the major NLUs support.
=> feat: Adding STENTOR.PERSON built-in entity

packages/stentor-runtime/src/main.ts
Simple fix for chats (stentor channel)
=> fixed channel nlu call in main

packages/stentor-runtime/src/translateEventAndContext.ts, packages/stentor/README.md, packages/stentor/package.json, packages/stentor/src/Assistant.ts, packages/stentor/src/__test__/Assistant.test.ts, packages/stentor/src/services/Secrets.ts, yarn.lock
Updates our secret service to pull the token from the AWS Secrets Manager
=> feat: Secret Service Update

packages/stentor-models/src/Request/IntentRequest.ts
This will make the results much more useful.
=> fix: Adds missing types to KnowledgeBaseResult

packages/stentor-models/src/Display/Card/Card.ts, packages/stentor-models/src/Display/List/List.ts, packages/stentor-models/src/Display/SimpleDisplay.ts, packages/stentor-models/src/Display/Types.ts
- Adds buttons to ListItems
- Adds beta feature to support templated lists when pulling from a data source
- Display items inherit from BaseDisplay interface
=> fit: Display Updates

packages/stentor/src/Assistant.ts, packages/stentor/src/__test__/Assistant.test.ts, packages/stentor/src/__test__/TestChannel.ts
Adds a test to ensure better coverage here.
=> fix: Adding Test to Assistant().lambda()

packages/stentor-models/src/Request/IntentRequest.ts
=> chore: Spelling in Knowledge Base Interface

packages/stentor-models/src/Services/KnowledgeBaseService.ts, packages/stentor-runtime/src/__test__/Mocks.ts, packages/stentor-service-event/src/__test__/EventService.test.ts
Made KB service (interface) async
=> KB services should be async

packages/stentor-models/src/Response/AbstractResponseBuilder.ts, packages/stentor-response/src/ResponseBuilder.ts, packages/stentor-response/src/__test__/ResponseBuilder.test.ts
This makes it easier to add custom displays which are needed for custom GUI components.  Just a little quality of life improvement.
=> fix: Adds withDisplay to the response builder

packages/stentor-models/src/NLU/NLUService.ts
=> Add config props to the NLU service

packages/stentor-models/src/NLU/NLUService.ts
Shortest pull request ever... sigh.
=> The setContext method is optional, not the parameter, you fool

packages/stentor-models/src/NLU/NLUService.ts
NLU may request different locales!
=> chore: Add locale to NLU Request

packages/stentor-models/src/Slot/Slot.ts
This will allow us to leverage the Lex Slot Obfuscation feature: https://docs.aws.amazon.com/lex/latest/dg/how-obfuscate.html
=> fix: Add slot obfuscations setting

packages/stentor-service-studio/package.json, packages/stentor-service-studio/src/Response.ts, packages/stentor-service-studio/src/StudioService.ts, packages/stentor-service-studio/src/__test__/README.md, packages/stentor-service-studio/src/__test__/StudioService.itest.ts
Updates the StudioService so it now implements KNowledgeBaseService by calling the /cms/question endpoint.
=> feat: Adds new /cms/question endpoint to the StudioService for KnowledgeBase Queries

packages/stentor-runtime/src/main.ts, packages/stentor-service-event/src/EventService.ts, packages/stentor-storage/src/createSessionStore.ts, packages/stentor-utils/src/request/getSlotValue.ts
Adds confidence scores to events when we have them.
Also fixes the create session store method to include transcript function.
=> fix: Add confidence scores to events when available

packages/stentor-models/src/NLU/NLUService.ts, packages/stentor-runtime/src/__test__/Mocks.ts, packages/stentor-runtime/src/__test__/main.nluservice.test.ts, packages/stentor-runtime/src/main.ts
These are pretty important if we then want to set context for a particular session.
=> chore:session store and user id on nlu service

packages/stentor-models/src/Handler/Handler.ts, packages/stentor-service-studio/src/Response.ts, packages/stentor-service-studio/src/StudioService.ts, packages/stentor-service-studio/src/__test__/StudioService.itest.ts, packages/stentor-utils/src/__test__/matcher.test.ts, packages/stentor-utils/src/matcher.ts
Updates the query method, which is used by the KnowledgebaseService interface, to include FAQs.
=> feat: Studio Service query with FAQs

packages/stentor-service-studio/README.md, packages/stentor/README.md, packages/stentor/src/__test__/Assistant.test.ts
Adding docs to studio service readme
=> chore: Studio Service Docs

packages/stentor-models/src/Runtime/Hooks.ts, packages/stentor-runtime/src/__test__/main.hooks.test.ts, packages/stentor-runtime/src/__test__/models/CustomContextHandler.ts, packages/stentor-runtime/src/main.ts, packages/stentor/src/Assistant.ts, packages/stentor/src/__test__/Assistant.test.ts
Adds a new optional hook for modifying the context after it is created.
=> fix: New hook for modifying context after creation

packages/stentor-guards/src/__test__/isIntent.test.ts, packages/stentor-guards/src/isIntent.ts, packages/stentor/src/index.ts
Updates isIntent to be a bit more modern and account for built-ins and overrides.
=> fix: Update isIntent

packages/stentor-models/src/Response/Response.ts
Adding a couple more system responses for future use on the chat-widget.
=> chore: A couple more system responses

packages/stentor-conditional/src/__test__/ConditionalDeterminer.test.ts, packages/stentor-determiner/src/__test__/determine.test.ts, packages/stentor-determiner/src/determine.ts, packages/stentor-models/src/Request/Request.ts, packages/stentor-runtime/src/__test__/main.eventservice.test.ts, packages/stentor-runtime/src/main.ts, packages/stentor-service-event/src/__test__/EventService.test.ts, packages/stentor-utils/src/compilers/__test__/compiler.test.ts, packages/stentor-utils/src/compilers/compiler.ts
Fixes conditional errors that occur when compiling conditions that result in undefined.  Now we will replace when a value is undefined instead of leaving it as is, which was the source of the error.
=> fix: Conditional Errors when compiling

.github/workflows/codeql.yml
=> chore: Setup codeql.yml

packages/stentor-utils/src/__test__/net.test.ts, packages/stentor-utils/src/dateTime.ts, packages/stentor-utils/src/net.ts
Adds support for telephone URLs in `isUrl` method.
=> fix: tel: support in isUrl

packages/stentor-constants/src/requests.ts, packages/stentor-guards/src/request/__test__/guards.test.ts, packages/stentor-guards/src/request/guards.ts, packages/stentor-models/src/Request/ChannelActionRequest.ts, packages/stentor-models/src/Request/Request.ts, packages/stentor-models/src/Request/Types.ts, packages/stentor-models/src/Request/index.ts
This will allow us to track URL clicks and potentially feedback responses like "Are you happy with this experience?" or "Was the above relevant to your question?"
=> feat: Channel Action Request

packages/stentor-request/src/Builders.ts, packages/stentor-runtime/src/__test__/main.eventservice.test.ts, packages/stentor-runtime/src/main.ts
This allows for better tracking of AudioPlayerPlaybackFailed events.
=> fix: Report AudioPlayer PlaybackFailed as error

packages/stentor-models/src/App/AppStatus.ts
This adds "Cancelled" status which we can use to stage cancellations while we clean up the resources.
=> fix: Cancelled App Status

packages/stentor-service-fetch/src/FetchService.ts
Lost node 14 support briefly.
Need to switch over to github actions where it is easier to test multiple node versions.
=> fix: Performance is not available in node 12 & node 14

packages/stentor-request/src/Builders.ts, packages/stentor-request/src/RequestConditionalCheck.ts, packages/stentor-request/src/__test__/RequestConditionalCheck.test.ts
New macro to use when we want to detect what webpage the user is currently on.
=> fix: New onWebPage macro

packages/stentor/package.json, packages/stentor/src/index.ts
This should simply the import statements.
=> chore: Adding a few more imports to main stentor package

packages/stentor-channel/src/Translators/TranslateToStentorResponse.ts, packages/stentor-channel/src/__tests__/TranslateToStentorResponse.test.ts, packages/stentor-runtime/src/main.ts
Adds more consistent error messages in stentor-runtime main() method.
=> fix: More consistent error messages

packages/stentor-models/src/Response/Response.ts, packages/stentor-utils/src/getResponseByTag.ts
Adds more official support for multiple tags on a response.
=> fix: Support for array of string on tags

packages/stentor-models/src/Services/KnowledgeBaseService.ts, packages/stentor-service-studio/package.json, packages/stentor-service-studio/src/StudioService.ts, packages/stentor-service-studio/src/__test__/StudioService.itest.ts
This will give us better control to cancel the requests if we need to.
=> fix: Adding Abort Controller options to KnowledgeBaseService interface

packages/stentor-conditional/src/ConditionalDeterminer.ts, packages/stentor-conditional/src/__test__/ConditionalDeterminer.test.ts, packages/stentor-determiner/src/determine.ts, packages/stentor-models/src/Request/KnowledgeBase.ts, packages/stentor-response/src/__test__/getResponse.test.ts, packages/stentor-response/src/determineResponse.ts, packages/stentor-response/src/getResponse.ts, packages/stentor-utils/src/compilers/__test__/compiler.test.ts, packages/stentor-utils/src/compilers/compiler.ts
This adds the ability for the ConditionalDeterminer to support the same macros we use in conditionals.
=> fix: Support for macros on Conditional Determiner

packages/stentor-service-studio/src/StudioService.ts
Should have included this in the previous PR.
=> fix: Adding type to our new RAG call on StudioService

packages/stentor-service-studio/src/StudioService.ts
Not sure how this worked at all.
=> fix: Double Encoding Query on RAG

packages/stentor-service-studio/src/StudioService.ts
Update to Studio Service to account for updated RAG endpoint.
=> fix: CMS RAG input, leverage hasAnswer & sources from endpoint

packages/stentor-models/src/Request/KnowledgeBase.ts, packages/stentor-models/src/Services/KnowledgeBaseService.ts, packages/stentor-service-studio/src/StudioService.ts
We had this on the RAG response but want to move this to the official Generated results.
=> fix: Add sources to KnowledgeBaseGenerated

packages/stentor-constants/src/storage.ts, packages/stentor-context/package.json, packages/stentor-context/src/ContextFactory.ts, packages/stentor-context/src/__test__/ContextFactory.test.ts, packages/stentor-models/src/NLU/NLUService.ts, packages/stentor-response/src/__test__/getResponse.test.ts, packages/stentor-runtime/src/__test__/main.eventservice.test.ts, packages/stentor-runtime/src/__test__/main.storage.test.ts, packages/stentor-runtime/src/getErrorResponse.ts, packages/stentor-runtime/src/main.ts, packages/stentor-user-storage-dynamo/src/__test__/DynamoUserStorage.test.ts, packages/stentor/src/__test__/Assistant.test.ts
Adds the ability to set session storage variable for filters and it will then be passed through to the NLU.
=> fix: Pass through NLU KB Filters

packages/stentor-models/src/index.ts
Can't export type on constants.
=> fix: Export Type on App Constants

packages/stentor-models/src/App/AppStatus.ts
Already using it, this is making it official:
=> fix: Ready for Install Status

packages/stentor-models/src/Crm.ts, packages/stentor-models/src/Services/CrmService.ts
This will allow us to track it and then update it later.
=> fix: Add refId to CRM Response and ExternalLead

packages/stentor-models/src/Services/CrmService.ts
We will need to update the CrmServices.
=> fix: Optional Update on CrmService

packages/stentor-models/src/NLU/NLUService.ts, packages/stentor-runtime/src/__test__/main.nluservice.test.ts, packages/stentor-runtime/src/main.ts, packages/stentor-service-event/src/__test__/EventService.test.ts
Allows NLUs to take the channel into effect when determining best response.
=> fix: Add Channel and Platform to NLURequestProps

packages/stentor-models/src/NLU/NLUService.ts, packages/stentor-runtime/src/main.ts
Going to see if we can leverage new Chat style APIs with NLUs
=> fix: Adding Transcripts to NLU Props

packages/stentor-models/src/NLU/NLUService.ts
This will allow us to pass through some more interesting parameters from the NLU.
=> fix: Attributes on NLURequests

packages/stentor-models/src/Services/CrmService.ts
=> fix: CrmService.getAvailability() proposal

packages/stentor-models/src/Crm.ts, packages/stentor-models/src/Services/CrmService.ts
One extra method to get the job type from the text description. And a config param for the "delayed" job types.
=> CRM model: more changes to support availability requests

packages/stentor-models/src/Request/KnowledgeBase.ts
Allows the GenAI to suggestion follow up queries.
=> fix: Add suggestion chips to a Generated AI Response

packages/stentor-utils/package.json, packages/stentor-utils/src/__test__/text.test.ts, packages/stentor-utils/src/index.ts, packages/stentor-utils/src/text.ts
Adds a couple of util methods to split sentences and pop questions.
=> fix: Utils - Sentence Splitter and Question Popper

package.json, packages/stentor-models/src/Display/MultistepForm.ts, packages/stentor-models/src/Display/index.ts, packages/stentor-models/src/Form/FormField.ts, packages/stentor-models/src/Form/FormStep.ts, packages/stentor-models/src/Form/index.ts, packages/stentor-models/src/index.ts
Pulling these out of other packages for easier sharing.
=> fix: Adding Form Models

packages/stentor-models/src/Display/Types.ts
=> fix: Adding MultistepForm as display

.github/workflows/claude-code-review.yml
Tells @claude to not review renovate PRs
=> chore: Update claude-code-review.yml
